services:
  foxtools:
    container_name: FoxTools
    restart: always
    image: ghcr.io/natroutter/foxtools:latest
    ports:
      - "127.0.0.1:3000:3000"
      #- "3000:3000"
    volumes:
      - app:/usr/src/app

volumes:
  app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./app