services:
  foxtools:
    container_name: FoxTools
    restart: always
    image: ghcr.io/natroutter/foxtools:latest
    environment:
      - PRIVATE_TOOL_PASSWORD=change_me
      - TURNSTILE_SECRET=change_me
      - TURNSTILE_SITEKEY=change_me
    ports:
      - 127.0.0.1:8400:3000
      #- 8400:3000